- name: install sysstat
  yum:
    name: sysstat
  become: true

- name: git clone fluentd-benchmark
  git:
    repo: https://github.com/okumin/fluentd-benchmark.git
    dest: "~/fluentd-benchmark-{{ item.label }}"
    version: "{{ item.branch }}"
  with_items: "{{ fluentd_versions }}"

- name: set ruby version
  shell: "rbenv local {{ item.ruby_version }}"
  args:
    chdir: "~/fluentd-benchmark-{{ item.label }}"
  with_items: "{{ fluentd_versions }}"

- name: fix fluentd version
  lineinfile:
    dest: "~/fluentd-benchmark-{{ item.label }}/in_forward/Gemfile"
    regexp: "^gem 'fluentd'"
    line: "gem 'fluentd', '{{ item.fluentd_version }}'"
  with_items: "{{ fluentd_versions }}"

- name: change the target host
  lineinfile:
    dest: "~/fluentd-benchmark-{{ item.label }}/one_forward/agent.conf"
    regexp: "      host 127.0.0.1 # FIX ME"
    line: "      host {{ receiver_host }}"
  with_items: "{{ fluentd_versions }}"
  when: is_sender

- name: enable multi process
  blockinfile:
    path: "~/fluentd-benchmark-{{ item.label }}/in_forward/receiver.conf"
    insertbefore: BOF
    line: |
      <system>
        workers #{ENV['FLUENTD_WORKERS']}
      </system>
  with_items: "{{ fluentd_versions }}"
  when: item.multi_worker_enabled

- name: bundle install
  shell: |
    rbenv rehash
    gem install bundler
    rbenv rehash
    bundle install
    rbenv rehash
  args:
    chdir: "~/fluentd-benchmark-{{ item.label }}/in_forward"
  with_items: "{{ fluentd_versions }}"
