- name: install sysstat
  yum:
    name: sysstat
  become: true

- name: git clone fluentd-benchmark
  git:
    repo: https://github.com/okumin/fluentd-benchmark.git
    dest: ~/fluentd-benchmark

- name: fix fluentd version
  lineinfile:
    dest: ~/fluentd-benchmark/in_forward/Gemfile
    regexp: "^gem 'fluentd'"
    line: "gem 'fluentd', '{{ fluentd_version }}'"
