- name: install sysstat
  yum:
    name: sysstat
  become: true

- name: git clone fluentd-benchmark
  git:
    repo: https://github.com/okumin/fluentd-benchmark.git
    dest: "~/fluentd-benchmark-{{ item.label }}"
  with_items: "{{ fluentd_versions }}"

- name: fix fluentd version
  lineinfile:
    dest: "~/fluentd-benchmark-{{ item.label }}/in_forward/Gemfile"
    regexp: "^gem 'fluentd'"
    line: "gem 'fluentd', '{{ item.version }}'"
  with_items: "{{ fluentd_versions }}"

- name: change the target host
  lineinfile:
    dest: "~/fluentd-benchmark-{{ item.label }}/one_forward/agent.conf"
    regexp: "host 127.0.0.1 # FIX ME"
    line: "{{ receiver_host }}"
  with_items: "{{ fluentd_versions }}"
  when: is_sender
