- name: install dependencies
  yum:
    name: "{{ item }}"
  with_items:
    - bzip2
    - wget
    - gcc
  become: true

- name: download jemalloc
  get_url:
    url: "https://github.com/jemalloc/jemalloc/releases/download/{{ jemalloc_version }}/jemalloc-{{ jemalloc_version }}.tar.bz2"
    dest: "~/jemalloc-{{ jemalloc_version }}.tar.bz2"

- name: decompress jemalloc
  shell: "bzip2 -dc jemalloc-{{ jemalloc_version }}.tar.bz2 | tar xvf -"
  args:
    chdir: "~/"

- name: rename jemalloc
  command: "mv ~/jemalloc-{{ jemalloc_version }} ~/jemalloc"

- name: make jemalloc
  shell: |
    ./configure --disable-debug
    make
  args:
    chdir: "~/jemalloc"
